executable = ./scripts/run/preprocess.sh
arguments = $(subject)

error = ./logs/$(subject)_preprocess.err
output = ./logs/$(subject)_preprocess.out
log = ./logs/$(subject)_preprocess.log

request_memory = 100000
request_disk = 10G
request_cpus = 50
request_gpus = 1
requirements = (TARGET.CUDACapability > 7.5 && UtsnameNodename =!= "g095" && UtsnameNodename =!= "g093" && TARGET.CUDAGlobalMemoryMb > 35000)

queue subject from ./scripts/run/jobs.txt